#!/bin/bash

# Update & Install
sudo apt update
sudo apt upgrade -y
sudo apt install curl git zsh vim gnome-shell gnome-tweak-tool unity-tweak-tool snapd -y
sudo apt autoremove

echo -e "\nWould you like to install""\e[34m PHP Storm, Bitwarden, Postman, Atom, Hyper.js & Spotify?\e[0m" "\e[33m Yes/No \e[0m"
read yesno
if [ "$yesno" = 'yes' ]; then
  echo -e "\e[32mInstalling Programs\e[0m""..."

  # Install Default Applications
  sudo snap install phpstorm --classic    #   web development
  sudo snap install bitwarden             #   password manager
  sudo snap install postman               #   api development
  sudo snap install atom --classic        #   web development -- free edition if you don't have a phpstorm license
  sudo snap install spotify               #   spotify music

  # Download hyper.js Terminal and Install
  curl -L https://releases.hyper.is/download/deb --output ~/Downloads/Hyper.deb
  sudo apt install -y ~/Downloads/Hyper.deb
  rm ~/Downloads/Hyper.deb
fi

echo -e "\nWould you like to install" "\e[34m Docker & Devilbox? \e[0m" "\e[33m Yes/No \e[0m"
read yesno
if [ "$yesno" = 'yes' ]; then
  echo -e "\e[32mInstalling Docker & Devilbox\e[0m""..."

  set +e
  # Install Docker
  sudo apt install docker -y
  sudo apt install docker-compose -y

  # Setup docker so it doesn't have to run as rootie mctootie
  sudo groupadd docker
  sudo gpasswd -a $USER docker
  sudo usermod -aG docker $USER
  newgrp docker
  sudo setfacl -m user:$USER:rw /var/run/docker.sock


  # Clone Devilbox & copy base env
  git clone https://github.com/cytopia/devilbox ~/Websites
  cp ~/ubuntu-dev-setup/.env ~/Websites/.env
  set -e
fi


echo -e "\nWould you like to install" "\e[34m OSX Theme? \e[0m" "\e[33m Yes/No \e[0m"
read yesno
if [ "$yesno" = 'yes' ]; then
  echo -e "\e[32mDownloading Repo\e[0m""..."

  mkdir ~/.themes
  mkdir ~/Themes
  git clone https://github.com/vinceliuice/Mojave-gtk-theme.git ~/Themes/Mojave-Dark
  cd ~/Themes/Mojave-Dark
  ./install.sh
fi


echo -e "\nWould you like to install" "\e[34m Oh My ZSH? \e[0m" "\e[33m Yes/No \e[0m"
read yesno
if [ "$yesno" = 'yes' ]; then
  echo -e "\e[32mInstalling Oh My ZSH\e[0m""..."

  # Install OH My ZSH
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

  # Fix % bug in hyper.js after Oh My ZSH Install
  echo 'unsetopt PROMPT_SP' >> ~/.zshrc
  chsh -s $(which zsh)
  echo -e "\e[34mLog Out User To Reset Shell?\e[0m" "\e[33m Yes/No \e[0m"
  read yesno
  if [ "$yesno" = 'yes' ]; then
    echo -e "\e[32mLogging Out\e[0m""..."
    # Logout the user so their shell is set to ZSH
    gnome-session-quit --no-prompt
  fi
fi
